### ISSUE TITLE
\newcommand*{} not supported

### ISSUE THREAD

**Issue by b-v** [d-krupke/flachtex#6]
It would be nice if the [starred](https://tex.stackexchange.com/questions/1050/whats-the-difference-between-newcommand-and-newcommand) version  \newcommand*{} could be supported, which does not seem to be the case at the moment.

**Comment by d-krupke** [comment]
You are right, this isn't supported right now. Should be an easy thing to do. I try to take care of it soon.

**Comment by d-krupke** [comment]
Should be fixed now. Please let me know, if it does not work as expected.

**Comment by b-v** [comment]
Thank you for the fix. If the command doesn't have any arguments, then it is indeed working now. 

However, if there are arguments such as `\newcommand*{\echoargument}[1]{#1}` then in the main text the `\echoargument{text}` would be replaced by `#1` (while one would expect `text`). The same would be the case for the unstarred version, `\newcommand{\echoargument}[1]{#1}`.

**Comment by d-krupke** [comment]
Interesting. Don't know why I didn't have a test case for that. Will fix it some day soon.

**Comment by d-krupke** [comment]
Finally found some time to fix it. Lost some time with it because I forgot that LaTeX-commands cannot have any numbers (and I did tests with commands like `\test1{}`). Should be working now, but I could only do some quick checks. I have to do some more extensive use of the tool myself soon, so potentially I will notice further bugs then.
